### ISSUE TITLE
bug: error on startup caused by `deleteNodeOperation`

### ISSUE THREAD

**Issue by ryanwolhuter** [powerhouse-inc/document-drive#25]
When updating to the latest version of the `document-drive` package (0.0.27), none of the files and drives render.

![Image](https://github.com/powerhouse-inc/document-drive/assets/39741965/42b4410d-d34c-4c1b-9813-e0d0bd6768e7)

The console has the following stack trace for the error:

```bash
Error occurred in handler for 'documentDrive:getDrive': Error: Node with id qFT6qoeNf3pOML1UnyIbX+x6Nig= not found
    at Object.deleteNodeOperation (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:11971:13)
    at ee$3 (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:12050:33)
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8543:16
    at Immer2.produce (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:636:20)
    at Gt$1 (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8542:68)
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8579:26
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8633:17
    at Array.reduce (<anonymous>)
    at Module.Qt [as replayDocument] (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8632:24)
    at DocumentDriveServer.getDrive (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:12662:26)
Error occurred in handler for 'documentDrive:getDrive': Error: Node with id yaONpVDuxls3r/vYcW1Uq8istTA= not found
    at Object.deleteNodeOperation (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:11971:13)
    at ee$3 (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:12050:33)
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8543:16
    at Immer2.produce (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:636:20)
    at Gt$1 (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8542:68)
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8579:26
    at /Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8633:17
    at Array.reduce (<anonymous>)
    at Module.Qt [as replayDocument] (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:8632:24)
    at DocumentDriveServer.getDrive (/Users/ry/powerhouse/document-model-electron/.vite/build/main.js:12662:26)
```

The error is `Error: Node with id qFT6qoeNf3pOML1UnyIbX+x6Nig= not found
    at Object.deleteNodeOperation`

The delete node operation is running at app startup.

**Comment by ryanwolhuter** [comment]
@acaldas @froid1911 not sure if you have already run across this, but documenting it here for vis

**Comment by acaldas** [comment]
This error was due to an old version of the document drive being in storage.
We should implement a way to handle this case to ease the release of new prototypes.
